analyzer:
  plugins:
    - custom_lint

custom_lint:
  # Forcibly disable lint rules by default
  enable_all_lint_rules: true
  rules:
    # You can now enable one specific rule in the "rules" list
    - missing_provider_scope
