name: fugi_movie_app_team2
description: Fugi Movie Apps Challange

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.3+2
  go_router: ^4.2.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
