name: fugi_movie_app_team2
description: Fugi Movie Apps Challange

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.10.0
  flutter_riverpod: ^2.0.0-dev.0
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  go_router: ^4.2.7
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.0-dev.0
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
  logger: ^1.1.0
  palette_generator: ^0.3.3+2
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-BoldItalic.ttf
    - assets/fonts/Poppins-Italic.ttf
    - assets/fonts/Poppins-Medium.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
